version: '2'
services:
    taskapp-app:
        image: taskapp
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://taskapp-mysql:3306/taskapp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    taskapp-mysql:
        extends:
            file: mysql.yml
            service: taskapp-mysql
